name: Build and Push

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  IMAGE_NAME: "ghcr.io/flipperdevices/welcomer-bot"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set image tag and name'
        id: tag
        run: |
          IMAGE_TAG="0.0.0"
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            REF=${{ github.ref }};
            TAG_FULL=${REF#refs/*/};
            IMAGE_TAG=${TAG_FULL//\//_};
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{steps.tag.outputs.image_name}}:${{steps.tag.outputs.image_tag}}
          cache-from: type=registry,ref=${{ steps.tag.outputs.image_name }}:buildcache
          cache-to: type=registry,ref=${{ steps.tag.outputs.image_name }}:buildcache,mode=max
